language: python
python:
  - 2.6
  - 2.7
  - pypy

env:
  - TOXENV=py26
  - TOXENV=py27,fuzz
  - TOXENV=pypy,fuzz

matrix:
  include:
    - python: 2.6
      env: TOXENV=py26
    - python: 2.7
      env: TOXENV=py27,fuzz
    - python: pypy
      env: TOXENV=pypy,fuzz

branches:
  only:
    - master

install:
  - "pip install tox"

script: tox
